AllCops:
  Include:
    - '**/Gemfile'
    - lib/**/*
    - spec/**/*
    - bamboo-worker.gemspec
  Exclude:
    - bin/**/*
    - files/**/*
    - templates/**/*
MethodLength:
  Exclude:
    - lib/**/*
ClassLength:
  Exclude:
    - lib/**/*
ParameterLists:
  Exclude:
    - lib/**/*
Metrics/CyclomaticComplexity:
  Severity: warning
  Max: 10
Metrics/PerceivedComplexity:
  Severity: warning
  Max: 10
